include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

#unit test and feature test:
#  stage: test
#  image: python:3.11
#  services:
#    - name: mariadb:11.5
#      alias: mariadb
#  variables:
#    MYSQL_ROOT_PASSWORD: 'dy9cAjyfhUpyaF7XuhzxzZ4a'
#  script:
#    - !reference [.add repositories, script]
#    - apt-get -y install sudo php php-zip php-dom php-xml php-mbstring php-gd php-curl php-mysql php-intl
#    # Test dependencies
#    - addgroup --gid 1000 test_nextcloud
#    - adduser --disabled-password --gecos "" --uid 1000 --gid 1000 test_nextcloud
#    - pip install --no-cache-dir -r requirements/test.txt
#    - pip install .
#    - sudo -u test_nextcloud pytest -n 10 --dist loadgroup -vvv --cov-branch --cov=cyberfusion.NextCloudSupport --cov-config=.coveragerc --cov-fail-under=95 --junitxml=report-pytest.xml
#      --database-username=root --database-password='dy9cAjyfhUpyaF7XuhzxzZ4a' --database-host=mariadb
#  artifacts:
#    reports:
#      junit: report-*.xml
